version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...
    - sed -i.bak "s/fabiant7t\/exips:latest/fabiant7t\/exips:{{ .Tag }}/g" deploy/deployment.yaml

builds:
  - id: exips
    main: ./cmd
    binary: exips
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .Commit }}
      - -X main.BuiltTime={{ .Date }}

dockers_v2:
  - id: app-docker
    dockerfile: Dockerfile.goreleaser
    ids:
      - exips
    images:
      - "docker.io/fabiant7t/exips"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - LICENSE
